services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: atletica-img
    container_name: atletica-container
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
    env_file:
      - .env
    ports:
      - "3000:5173"
    command: npm run dev

    
  db:
    image: postgres:16.4
    container_name: atletica-postgres-container
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - atletica-dev-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"

volumes:
  atletica-dev-data: